columns:
 - CreditScore : int
 - Geography : category
 - Gender : category
 - Age : int
 - Tenure : int
 - Balance : int
 - NumOfProducts : int
 - HasCrCard : int
 - IsActiveMember : int 
 - RowNumber : int
 - CustomerId : int
 - Surname : category

numerical_columns:
 - Tenure 
 - Balance 
 - NumOfProducts
 - HasCrCard 
 - IsActiveMember
 - CreditScore 
 - Age

categorical_columns:
 - Gender 
 - Geography

drop_columns:
 - RowNumber
 - CustomerId
 - Surname

oh_columns:
 - Gender
 - Geography
